[package]
name = "web-app-oidc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1"
time = "0.3"
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1.0"
rustls = "0.23"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-sessions = "0.15"
axum = {  version = "0.8", features = ["macros", "original-uri"] }
axum-server = { version = "0.8", features = [ "tls-rustls-no-provider"] }
axum-oidc = "1.0.0-dev-2"
openidconnect = "4"
axum-template = {  version = "3", features = ["minijinja"] }
dotenvy = "0.15"
minijinja = "2"

# instrumentation and logging
tracing = "0.1"
tracing-bunyan-formatter = "0.3"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-futures = { version = "0.2", features = ["futures-03"] }
tracing-log = "0.2.0"
telemetry = "0.1.3"
minijinja-embed = "2.14.0"

[build-dependencies]
minijinja-embed = "2.14.0"
